name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - '**' # matches every branch
      - '!master' # excludes master
      - '!main' # excludes main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore SRWE.sln

      - name: Build Release
        run: msbuild SRWE.sln /p:Configuration=Release /p:Platform=x86

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: SRWE-Release
          path: SRWE/bin/Release/
